version: '3'

services:
  db:
    image: postgres  # Using PostgreSQL version 13, but you can choose another version if needed
    ports:
      - "5432:5432"    # Map PostgreSQL port
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rdISTD7
      POSTGRES_DB: foodsubscription